# Generated by Django 3.1.7 on 2021-05-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_id',
            new_name='track_uri',
        ),
    ]
