# Generated by Django 3.1.7 on 2021-05-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20210509_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.CharField(default='', max_length=400),
        ),
    ]
