# Generated by Django 4.2.21 on 2025-05-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('tracks', '0003_track_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='artists.artist'),
        ),
    ]
