# Generated by Django 4.2.21 on 2025-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_alter_track_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='filename',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
