# Generated by Django 4.2.11 on 2025-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_trackview_trackplay_tracklike_trackimpression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(blank=True, max_length=400, null=True)),
                ('filename', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='s3_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
