# Generated by Django 4.2.11 on 2025-05-07 05:40

from django.conf import settings
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_remove_photo_thumbnail_remove_photo_uploaded_poster_and_more'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0004_video_filename_video_s3_key_videoplaylist_title'),
        ('tracks', '0006_trackv2_track_s3_key'),
        ('posts', '0003_encodeprofile_post_description_post_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoencoding',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='videoencoding',
            name='video',
        ),
        migrations.RenameField(
            model_name='postdislike',
            old_name='dislike_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='liked_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='friendly_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='post_dislikes', through='posts.PostDislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to=posts.models.post_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='impressions',
            field=models.ManyToManyField(blank=True, related_name='post_impressions', through='posts.PostImpression', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', through='posts.PostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, through='posts.PostPhoto', to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='playlists',
            field=models.ManyToManyField(blank=True, through='posts.PostPlaylist', to='playlists.playlist'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tracks',
            field=models.ManyToManyField(blank=True, through='posts.PostTrack', to='tracks.track'),
        ),
        migrations.AlterField(
            model_name='post',
            name='videos',
            field=models.ManyToManyField(blank=True, through='posts.PostVideo', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', through='posts.PostView', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EncodeProfile',
        ),
        migrations.DeleteModel(
            name='VideoEncoding',
        ),
    ]
