# Generated by Django 4.2.4 on 2023-11-14 17:05

from django.db import migrations, models
import django.db.models.deletion
import posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='sprites',
            field=models.FileField(blank=True, max_length=500, upload_to=posts.helpers.original_thumbnail_file_path),
        ),
        migrations.CreateModel(
            name='VideoPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=1)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videoplaylist')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='videos',
            field=models.ManyToManyField(through='videos.VideoPlaylistItem', to='videos.video'),
        ),
    ]
