# Generated by Django 3.2.23 on 2023-12-09 21:31

from django.db import migrations, models
import posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoplaylist_video_sprites_videoplaylistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=500, upload_to=posts.helpers.original_thumbnail_file_path),
        ),
    ]
