# Generated by Django 4.2.11 on 2025-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='s3_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='title',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
