# Generated by Django 4.2.11 on 2024-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('favicon', models.FileField(blank=True, upload_to='favicons/')),
            ],
        ),
    ]
