# Generated by Django 4.0 on 2023-06-01 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=90)),
                ('description', models.TextField(blank=True, help_text='description')),
                ('add_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('friendly_token', models.CharField(blank=True, max_length=12)),
                ('banner_logo', imagekit.models.fields.ProcessedImageField(blank=True, default='userlogos/banner.jpg', upload_to='userlogos/%Y/%m/%d')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='users.user')),
            ],
        ),
    ]
