# Generated by Django 4.2.21 on 2026-07-09 02:36

from django.db import migrations, models
from django.utils.text import slugify


def populate_handles(apps, schema_editor):
    Community = apps.get_model('communities', 'Community')
    for c in Community.objects.filter(handle=''):
        handle = slugify(c.name)[:100]
        if not handle:
            handle = f'community-{c.id}'
        # ensure uniqueness
        existing = Community.objects.filter(handle=handle).exclude(id=c.id).first()
        if existing:
            handle = f'{handle}-{c.id}'
        c.handle = handle
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='handle',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.RunPython(populate_handles, migrations.RunPython.noop),
    ]
