# Generated by Django 3.1.7 on 2021-05-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_id',
            new_name='album_uri',
        ),
    ]
