# Generated by Django 4.0 on 2023-06-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_alter_album_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
