# Generated by Django 4.2.4 on 2023-11-12 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import posts.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('photo_file', models.FileField(upload_to='media_files/photos/')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, max_length=500, upload_to=posts.helpers.original_thumbnail_file_path)),
                ('uploaded_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, max_length=500, upload_to=posts.helpers.original_thumbnail_file_path)),
                ('uploaded_poster', imagekit.models.fields.ProcessedImageField(blank=True, max_length=500, upload_to=posts.helpers.original_thumbnail_file_path, verbose_name='Upload image')),
                ('user_featured', models.BooleanField(default=False)),
                ('friendly_token', models.CharField(blank=True, db_index=True, max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
