# Generated by Django 4.2.21 on 2025-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('attached', 'Attached')], default='draft', max_length=20),
        ),
    ]
