# Generated by Django 4.2.4 on 2023-11-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0002_photoview_photolike_photoimpression_photodislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(blank=True, help_text='description')),
                ('friendly_token', models.CharField(blank=True, db_index=True, max_length=12)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now=True)),
                ('ordering', models.IntegerField(default=1)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
                ('photo_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photoalbum')),
            ],
            options={
                'ordering': ['ordering', '-action_date'],
            },
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='photo',
            field=models.ManyToManyField(blank=True, through='photos.PhotoAlbumItem', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoalbums', to=settings.AUTH_USER_MODEL),
        ),
    ]
