# Generated by Django 4.2.11 on 2025-05-07 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0003_photoalbum_photoalbumitem_photoalbum_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_poster',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_thumbnail',
        ),
        migrations.AddField(
            model_name='photo',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='photo_dislikes', through='photos.PhotoDislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='filename',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='impressions',
            field=models.ManyToManyField(blank=True, related_name='photo_impressions', through='photos.PhotoImpression', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='photo_likes', through='photos.PhotoLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='s3_key',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='photo_views', through='photos.PhotoView', to=settings.AUTH_USER_MODEL),
        ),
    ]
