# Generated by Django 4.2.21 on 2026-07-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_profile_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
