# Generated by Django 4.2.21 on 2026-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_add_todolist_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todolist',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
