# Generated by Django 4.2.21 on 2025-05-22 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('videos', '0001_initial'),
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagevideo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video'),
        ),
        migrations.AddField(
            model_name='messagetrack',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.message'),
        ),
        migrations.AddField(
            model_name='messagetrack',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.track'),
        ),
        migrations.AddField(
            model_name='messagephoto',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.message'),
        ),
        migrations.AddField(
            model_name='messagephoto',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chats.chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='photo_messages', through='chats.MessagePhoto', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='message',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='track_messages', through='chats.MessageTrack', to='tracks.track'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='video_messages', through='chats.MessageVideo', to='videos.video'),
        ),
    ]
