# Generated by Django 4.2.11 on 2024-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='name',
        ),
        migrations.AddField(
            model_name='query',
            name='query_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='suggestion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
