# Generated by Django 3.1.7 on 2021-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('artist_id', models.CharField(max_length=300)),
                ('album', models.ManyToManyField(related_name='artists', to='albums.Album')),
            ],
        ),
    ]
