# Generated by Django 3.1.7 on 2021-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='track',
            field=models.ManyToManyField(related_name='artists', to='tracks.Track'),
        ),
    ]
