# Generated by Django 3.1.7 on 2021-04-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='album',
            new_name='albums',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='track',
            new_name='tracks',
        ),
    ]
