# Generated by Django 3.1.7 on 2021-05-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20210422_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='tracks',
        ),
    ]
