# Generated by Django 3.1.7 on 2021-05-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20210508_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_id',
            new_name='artist_uri',
        ),
    ]
