# Generated by Django 4.0 on 2023-06-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('albums', '0009_albumtrack'),
        ('users', '0002_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', related_query_name='view', to='albums.album')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', related_query_name='view', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed', to='users.user')),
            ],
        ),
    ]
