# Generated by Django 4.0 on 2023-06-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='album',
        ),
    ]
