# Generated by Django 4.2.4 on 2023-11-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_remove_view_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
