# Generated by Django 3.2.23 on 2023-12-11 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20231210_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='impressions',
            field=models.ManyToManyField(blank=True, related_name='movie_impressions', through='movies.MovieImpression', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='movie_views', through='movies.MovieView', to=settings.AUTH_USER_MODEL),
        ),
    ]
