# Generated by Django 3.2.23 on 2023-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20231211_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
