name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m venv env



    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem

        chmod 600 key.pem

        ssh -i key.pem ubuntu@$EC2_PUBLIC_IP -o StrictHostKeyChecking=no << 'EOF'

          sudo apt update
          sudo apt install -y python3 python3-venv python3-pip

          cd /home/ubuntu/litloop_backend_v2
          git pull origin main

          if [ ! -d "env" ]; then
            python3 -m venv env
          fi

          source env/bin/activate

          pip install -r requirements/base.txt

          export DJANGO_SETTINGS_MODULE=litloop_backend_v2.settings.prod

          python3 manage.py migrate

          sudo cp /home/ubuntu/litloop_backend_v2/deploy/gunicorn/gunicorn.service /etc/systemd/system/gunicorn.service

          sudo systemctl daemon-reload
          sudo systemctl enable gunicorn
          sudo systemctl restart gunicorn
        EOF
