name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m venv env
        


    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem

        chmod 600 key.pem

        ssh -i key.pem ubuntu@$EC2_PUBLIC_IP -o StrictHostKeyChecking=no << 'EOF'
          cd /home/ubuntu/litloop_backend_v2
          git pull origin main
          source venv_3.9/bin/activate
          pip install -r requirements.txt
          export DJANGO_SETTINGS_MODULE=litloop_backend_v2.settings.prod
          python manage.py migrate
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
